### ISSUE TITLE
Presence simulation ignores switch

### ISSUE THREAD

**Issue by ginkel** [slashback100/presence_simulation#123] opened 2024-04-09 20:46 UTC
Hi there,

recently (probably since the most recent update) the presence simulation seems to ignore its switch, i.e., lights are controlled automatically despite the switch being turned off. Enabling the debug log unfortunately did not lead to any insights.

Currently running v4.5.

Any ideas?

Thanks,
Thilo

**Comment by slashback100** [comment] 2024-04-09 21:14
I don't observe the same behavior with v4.5 and latest HA version (2024.4.2). 
Could you anyway send me the debug logs after turning off the switch please?

**Comment by slashback100** [comment] 2024-04-09 21:15
Do you have several simulation switches or just one?

**Comment by PablaV** [comment] 2024-04-16 00:42
Think I have the same issue, the switch is off (I only have one switch) however lights are turning on and off. I look at the history of the light that turned on/off and it says it was turned on/off by scene activate. The only scene I have configured is the scene that is created by the integration. I can grab logs if needed but there seems to be some disconnect between the state of the switch and the simulation turning on and off.

**Comment by PablaV** [comment] 2024-04-29 03:57
I think I figured out what the issue is exactly, opened a [new issue](https://github.com/slashback100/presence_simulation/issues/130) here just in case its not the same as originally desired

**Comment by slashback100** [comment] 2024-04-29 13:29
@ginkel, is it the same issue described by PablaV in #130 that you have ?

**Comment by ginkel** [comment] 2024-04-29 13:54
> @ginkel, is it the same issue described by PablaV in #130 that you have ?

I'm not 100% certain as I haven't been able to obtain meaningful debug logs, but that quite plausible.

**Comment by slashback100** [comment] 2024-04-30 19:35
Ok, since I have no information on a potential other issue, I will close this one. Feel free to re-open if you have new information that can help me investigating.

**Closed by slashback100** 2024-04-30 19:35 UTC
