### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Wright55** [slashback100/presence_simulation#102] opened 2023-11-15 17:37 UTC
Noticed last few days when I have wanted lights to come on whilst away from home, lights were not activating. I generally use within an automation, but have tested manually.

This is the log

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/presence_simulation/__init__.py:341
Integration: Presence Simulation (documentation, issues)
First occurred: 13 November 2023 at 10:44:58 (150 occurrences)
Last logged: 15:02:58

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/presence_simulation/__init__.py", line 301, in simulate_single_entity
    await update_entity(entity_id, state)
  File "/config/custom_components/presence_simulation/__init__.py", line 341, in update_entity
    color_mode = color_mode+"_color"
                 ~~~~~~~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by slashback100** [comment] 2023-11-17 10:32
Duplicate of #99

**Closed by slashback100** 2023-11-17 10:32 UTC
